config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
	root 'welcome#index'

	resources :categories do 
	 resources :foods
	end
	resources :foods do
		get :who_bought, on: :member
	end
end

app/models/food.rb
class Food < ApplicationRecord
	belongs_to :category
	has_many :line_items
	has_many :orders, through: :line_items
	before_destroy :ensure_not_referenced_by_any_line_item
	validates :title, :image, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	has_attached_file :image, styles: { large: "600x600>" }, 
		:path => ":rails_root/public/system/:image/:id/:style/:filename",
    	:url => "/system/:image/:id/:style/:filename"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	private

		# ensure that there are no line items referencing this product
		def ensure_not_referenced_by_any_line_item
			unless line_items.empty?
				errors.add(:base, 'Line Items present')
				throw :abort
			end
		end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  def index
	@foods = Food.order(:title)
  end 

  def show
  end

  def new
    @food = Food.new
  end

  def edit
  end

  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to root_url }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to root_url }
        
        @foods = Food.all
        ActionCable.server.broadcast 'foods',
          html: render_to_string('welcome/index', layout: false)
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
    end
  end

  def who_bought
    @food = Food.find(params[:id])
    @latest_order = @food.orders.order(:updated_at).last
      if stale?(@latest_order)
        respond_to do |format|
        format.atom
      end
    end
  end

  private

    def set_category 
      @category = Category.find(params[:category_id])
    end 

    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:title, :description, :price, :image, :category_id)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for([@category, @food]) do |f| %>
	<% if food.errors.any? %>
		<div id="error_explanation" style="color: #444">
			<h2><%= pluralize(food.errors.count, "error") %>
				prohibited this food from being saved:</h2>
			<ul>
				<% food.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
	    <%= f.label :category %>
	    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Categorie" } %>
  	</div>

	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, rows: 10, cols: 60, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label "price ( DIRHAM )" %>
		<%= f.text_field :price, class: "form-control" %>
	</div>
	<div class="field">
      <%= f.file_field :image %>
    </div>
	<div class="actions">
		<%= f.submit class: "red-btn" %>
	</div>
<% end %>

app/views/foods/edit.hrml.erb
<div class="container">
	<h1>Edit Food</h1>
	<%= render 'form', food: @food %>
</div>

app/views/foods/edit.html.erb
<div class="container">
	<h1>Edit Food</h1>
	<%= render 'form', food: @food %>
</div>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<table>
<% @foods.each do |food| %>
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
<td>
<%= image_tag(food.image.url(:large), class: 'list_image') %>
</td>
<td class="list_description">
<dl>
<dt><%= food.title %></dt>
<dd><%= truncate(strip_tags(food.description),
length: 80) %></dd>
</dl>
</td>
<td class="list_actions">
<%= link_to 'Show', food %><br/>
<%= link_to 'Edit', edit_food_path(food) %><br/>
<%= link_to 'Destroy', food, method: :delete,
data: { confirm: 'Are you sure?' } %>
</td>
</tr>
<% end %>
</table>
<br />
<%= link_to 'New food', new_food_path %>

app/views/foods/new.html.erb
<div class="container">
	<div class="col-md-6">
		<h2 style="color: black; margin-top: 20px;">New Food</h2>
		<%= render 'form', food: @food %>
	</div>
</div>